run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    # Allow unchecked errors in defer statements
    - linters: [errcheck]
      source: "defer"
    # Allow unchecked errors in test files
    - path: _test\.go
      linters: [errcheck]
